#!/usr/bin/env python3
"""
responder_api.py — RedMicro API Wrapper for responder

Auto-generated by the RedMicro API Wrapper Generator (CLI-Anything inspired).

This exposes responder as a clean, structured JSON API so agents can call it reliably.

Run with:
    uvicorn responder_api:app --reload --port 8000

Then call:
    curl -X POST "http://localhost:8000/responder" -H "Content-Type: application/json" -d '{
  "target": "10.10.10.50",
  "options": {
    "mode": "fast"
  }
}'
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional, Any, Dict
import subprocess
import json

app = FastAPI(
    title="RedMicro responder API",
    description="Agent-native API wrapper for responder. Generated by RedMicro API Harness system.",
    version="1.0.0"
)


class ResponderRequest(BaseModel):
    """Request model — customize per tool."""
    target: Optional[str] = None
    input: Optional[Dict[str, Any]] = None
    options: Optional[Dict[str, Any]] = None


class ResponderResponse(BaseModel):
    """Standard RedMicro response envelope."""
    status: str
    tool: str = "responder"
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


@app.post("/responder", response_model=ResponderResponse)
async def call_responder(request: ResponderRequest):
    """
    Main callable endpoint for agents / orchestrators.
    """
    try:
        # === Replace this block with real invocation logic ===
        # Example: call the corresponding CLI harness
        cmd = ["python", "../cli-harness/responder_harness.py", "--input", json.dumps(request.dict())]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

        if proc.returncode != 0:
            raise Exception(proc.stderr or "Tool failed")

        try:
            parsed = json.loads(proc.stdout)
        except:
            parsed = {"raw_output": proc.stdout}

        return ResponderResponse(
            status="success",
            result=parsed
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
async def health():
    return {"status": "ok", "tool": "responder"}


# For direct testing
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
