//! Native (non-Python) emitters for Rust (axum) and Go (stdlib http).
//!
//! These produce immediately buildable / runnable projects that expose
//! the same request/response contract as the RedMicro Python generators:
//!   POST /<tool>/run  { target?, input?, options? } -> { status, tool, result?, error? }
//!   GET  /health
//!
//! The output is a small self-contained project directory so `cargo run` / `go run .` works.

use anyhow::{Context, Result};
use std::path::Path;
use tokio::fs;

/// Generate a minimal, compilable Rust + axum server project for the tool.
/// Produces: <out_dir>/Cargo.toml + <out_dir>/src/main.rs + <out_dir>/README.md
pub async fn generate_rust_axum(
    tool_name: &str,
    _description: &str,
    out_dir: &Path,
) -> Result<Vec<crate::generator::python_bridge::GeneratedArtifact>> {
    let snake = sanitize(tool_name);
    let kebab = tool_name.replace('_', "-");
    let project_name = format!("{}-api", kebab);

    fs::create_dir_all(out_dir.join("src")).await?;

    // Cargo.toml - pinned to recent but widely compatible axum 0.7/0.8 range
    let cargo = format!(
        r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {{ version = "0.7", features = ["json"] }}
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
"#,
        project_name.replace('-', "_")
    );

    let main_rs = format!(
        r#"//! {tool} API — native Rust axum server generated by api-anything
//! Matches the RedMicro Python API contract for agent interoperability.

use axum::{{
    extract::Json,
    routing::{{get, post}},
    Router,
}};
use serde::{{Deserialize, Serialize}};
use std::net::SocketAddr;

#[derive(Debug, Deserialize)]
pub struct {cap}Request {{
    pub target: Option<String>,
    pub input: Option<serde_json::Value>,
    pub options: Option<serde_json::Value>,
}}

#[derive(Debug, Serialize)]
pub struct {cap}Response {{
    pub status: String,
    pub tool: String,
    pub result: Option<serde_json::Value>,
    pub error: Option<String>,
}}

async fn run_{snake}(Json(req): Json<{cap}Request>) -> Json<{cap}Response> {{
    // Stub implementation — replace with real tool invocation / harness call.
    // This preserves exact shape expected by callers and the TUI/ACP.
    let result = serde_json::json!({{
        "echo": req,
        "note": "Native Rust axum backend (api-anything native emitter)"
    }});

    Json({cap}Response {{
        status: "success".into(),
        tool: "{tool}".into(),
        result: Some(result),
        error: None,
    }})
}}

async fn health() -> Json<serde_json::Value> {{
    Json(serde_json::json!({{ "status": "ok", "tool": "{tool}", "backend": "rust-axum" }}))
}}

#[tokio::main]
async fn main() {{
    let app = Router::new()
        .route("/{snake}/run", post(run_{snake}))
        .route("/health", get(health));

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("{tool} native axum API listening on http://{{}}", addr);
    println!("Try: curl -X POST http://127.0.0.1:8080/{snake}/run -H 'content-type: application/json' -d '{{\"target\":\"demo\"}}'");

    // Modern axum 0.7+ server start (reliable for `cargo check`)
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}}
"#,
        tool = tool_name,
        cap = capitalize(&snake),
        snake = snake,
    );

    let readme = format!(
        r#"# {project_name}

Native Rust (axum) API wrapper for {tool_name}.

Generated by api-anything native emitter — identical contract to the Python FastAPI version.

## Run

```bash
cargo run
```

Server starts on :8080.

## Endpoints

- POST /{snake}/run
  Body: {{"target": "...", "input": {{...}}, "options": {{...}}}}

- GET /health

Response shape:
{{"status":"success","tool":"{tool_name}","result":{{...}},"error":null}}

Matches RedMicro absorb / api_wrapper_generator output for seamless agent use.
"#,
        project_name = project_name,
        tool_name = tool_name,
        snake = snake,
    );

    let cargo_path = out_dir.join("Cargo.toml");
    let main_path = out_dir.join("src/main.rs");
    let readme_path = out_dir.join("README.md");

    fs::write(&cargo_path, cargo)
        .await
        .context("write Cargo.toml")?;
    fs::write(&main_path, main_rs)
        .await
        .context("write src/main.rs")?;
    fs::write(&readme_path, readme)
        .await
        .context("write README")?;

    // Also ensure a basic .gitignore for niceness (no dead files)
    let gitignore = out_dir.join(".gitignore");
    fs::write(&gitignore, "target/\nCargo.lock\n").await.ok();

    Ok(vec![
        crate::generator::python_bridge::GeneratedArtifact {
            path: cargo_path,
            kind: "rust-cargo".to_string(),
            size: 0, // filled by caller if needed; real size not critical for native path
        },
        crate::generator::python_bridge::GeneratedArtifact {
            path: main_path,
            kind: "rust-axum".to_string(),
            size: 0,
        },
        crate::generator::python_bridge::GeneratedArtifact {
            path: readme_path,
            kind: "rust-readme".to_string(),
            size: 0,
        },
    ])
}

/// Generate a minimal, runnable Go HTTP server (stdlib only) with identical contract.
pub async fn generate_go_http(
    tool_name: &str,
    _description: &str,
    out_dir: &Path,
) -> Result<Vec<crate::generator::python_bridge::GeneratedArtifact>> {
    let snake = sanitize(tool_name);
    let kebab = tool_name.replace('_', "-");
    let module_name = format!("{}-api", kebab);

    fs::create_dir_all(out_dir).await?;

    let go_mod = format!(
        r#"module {}

go 1.21
"#,
        module_name
    );

    let main_go = format!(
        r#"// {tool} API — native Go HTTP server generated by api-anything
// Contract-compatible with RedMicro Python generators and Rust axum emitter.

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
)

type {cap}Request struct {{
	Target  *string         `json:"target"`
	Input   json.RawMessage `json:"input"`
	Options json.RawMessage `json:"options"`
}}

type {cap}Response struct {{
	Status string          `json:"status"`
	Tool   string          `json:"tool"`
	Result interface{{}}   `json:"result,omitempty"`
	Error  *string         `json:"error,omitempty"`
}}

func runHandler(w http.ResponseWriter, r *http.Request) {{
	var req {cap}Request
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {{
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}}

	result := map[string]interface{{}}{{
		"echo": map[string]interface{{}}{{
			"target":  req.Target,
			"input":   req.Input,
			"options": req.Options,
		}},
		"note": "Native Go stdlib backend (api-anything)",
	}}

	resp := {cap}Response{{
		Status: "success",
		Tool:   "{tool}",
		Result: result,
	}}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}}

func healthHandler(w http.ResponseWriter, r *http.Request) {{
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{{"status":"ok","tool":"{tool}","backend":"go-stdlib"}}`)
}}

func main() {{
	http.HandleFunc("/{snake}/run", runHandler)
	http.HandleFunc("/health", healthHandler)

	addr := ":8080"
	fmt.Printf("{tool} native Go API listening on http://0.0.0.0%s\n", addr)
	fmt.Printf("Try: curl -X POST http://127.0.0.1:8080/{snake}/run -d '{{\"target\":\"demo\"}}'\n")
	log.Fatal(http.ListenAndServe(addr, nil))
}}
"#,
        tool = tool_name,
        cap = capitalize(&snake),
        snake = snake,
    );

    let readme = format!(
        r#"# {module_name}

Native Go (stdlib net/http) API wrapper for {tool_name}.

## Run

```bash
go run .
# or: go run main.go
```

## Endpoints (identical contract)

POST /{snake}/run
GET  /health

Response envelope matches the Python and Rust emitters exactly.
"#,
        module_name = module_name,
        tool_name = tool_name,
        snake = snake,
    );

    let mod_path = out_dir.join("go.mod");
    let main_path = out_dir.join("main.go");
    let readme_path = out_dir.join("README.md");

    fs::write(&mod_path, go_mod).await?;
    fs::write(&main_path, main_go).await?;
    fs::write(&readme_path, readme).await?;

    Ok(vec![
        crate::generator::python_bridge::GeneratedArtifact {
            path: mod_path,
            kind: "go-mod".to_string(),
            size: 0,
        },
        crate::generator::python_bridge::GeneratedArtifact {
            path: main_path,
            kind: "go-http".to_string(),
            size: 0,
        },
        crate::generator::python_bridge::GeneratedArtifact {
            path: readme_path,
            kind: "go-readme".to_string(),
            size: 0,
        },
    ])
}

fn sanitize(s: &str) -> String {
    s.to_lowercase()
        .replace('-', "_")
        .replace(' ', "_")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '_')
        .collect()
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
